### ISSUE TITLE
Complete some tasks

### ISSUE THREAD

**Issue by tari404** [tari404/test-repo#5]
### TODO:
1. balabala~
2. balabala~

**Comment by helloDoraHacks** [comment]
The issue has been marked as a [HackerLink Bounty](https://hackerlink.io/bounty/2).

* Bonus: **0.2** ETH

* Deadline: 2020-09-11T02:37:00.000Z

Record on the blockchain: `0x5650fb71a855da9c8acf412fa43d411955d9758b2242587433150cb62406f045`

**Comment by tari404** [comment]
Try to fix it
